#!/usr/bin/env python3
"""
Generate admin_html.h from data/admin.html

This script:
1. Reads data/admin.html
2. Compresses it with gzip (level 9)
3. Generates src/admin_html.h with the compressed data as PROGMEM array

Used as a PlatformIO pre-build script.
"""

import gzip
import os
import sys

# When run as PlatformIO script
try:
    Import("env")
    is_platformio = True
except:
    is_platformio = False

def get_project_dir():
    """Get project root directory"""
    if is_platformio:
        return env.get("PROJECT_DIR", os.getcwd())
    # When run standalone, go up from scripts/ to project root
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def generate_admin_html(*args, **kwargs):
    """Generate admin_html.h from data/admin.html"""
    project_dir = get_project_dir()

    source_file = os.path.join(project_dir, 'data', 'admin.html')
    output_file = os.path.join(project_dir, 'src', 'admin_html.h')

    # Read version from config.h
    config_file = os.path.join(project_dir, 'src', 'config.h')
    version = "1.2.0"  # Default
    try:
        with open(config_file, 'r') as f:
            for line in f:
                if '#define FIRMWARE_VERSION' in line:
                    # Extract version from: #define FIRMWARE_VERSION "1.2.0"
                    version = line.split('"')[1]
                    break
    except:
        pass

    print(f"[admin_html] Generating {output_file}")
    print(f"[admin_html] Source: {source_file}")
    print(f"[admin_html] Version: {version}")

    if not os.path.exists(source_file):
        print(f"[admin_html] WARNING: {source_file} not found, skipping generation")
        return

    # Read source file
    with open(source_file, 'rb') as f:
        content = f.read()

    original_size = len(content)

    # Compress with maximum compression
    compressed = gzip.compress(content, compresslevel=9)
    compressed_size = len(compressed)

    print(f"[admin_html] Original: {original_size} bytes")
    print(f"[admin_html] Compressed: {compressed_size} bytes ({100*compressed_size//original_size}%)")

    # Generate header file
    with open(output_file, 'w') as f:
        f.write('/**\n')
        f.write(' * Auto-generated from data/admin.html\n')
        f.write(' * DO NOT EDIT - this file is generated by scripts/generate_admin_html.py\n')
        f.write(' *\n')
        f.write(f' * Original size: {original_size} bytes\n')
        f.write(f' * Compressed size: {compressed_size} bytes\n')
        f.write(' */\n\n')
        f.write('#ifndef ADMIN_HTML_H\n')
        f.write('#define ADMIN_HTML_H\n\n')
        f.write('#include <Arduino.h>\n\n')
        f.write(f'const size_t admin_html_gz_len = {compressed_size};\n')
        f.write(f'const char* admin_html_version = "{version}";\n\n')
        f.write('const uint8_t admin_html_gz[] PROGMEM = {\n')

        # Write bytes in rows of 16
        for i, b in enumerate(compressed):
            if i % 16 == 0:
                f.write('    ')
            f.write(f'0x{b:02x}')
            if i < len(compressed) - 1:
                f.write(', ')
            if i % 16 == 15:
                f.write('\n')

        if len(compressed) % 16 != 0:
            f.write('\n')

        f.write('};\n\n')
        f.write('#endif // ADMIN_HTML_H\n')

    print(f"[admin_html] Generated {output_file}")

# Register as PlatformIO pre-build action
if is_platformio:
    env.AddPreAction("buildprog", generate_admin_html)

# Allow running standalone for testing
if __name__ == "__main__":
    generate_admin_html()
